### ISSUE TITLE
RAG Deploy failed.

### ISSUE THREAD

**Issue by luozhangwen** [NVIDIA-NIM-Agent-Blueprints/digital-human#3]
[https://github.com/NVIDIA-NIM-Agent-Blueprints/digital-human/blob/main/deploy/README.md#rag-pipeline-deployment](url)

Deploy the RAG Pipeline
3.Deploy the RAG pipeline.
`USERID=$(id -u) docker compose --profile local-nim --profile milvus up -d`

What‘s folder execute for this commend?  Doesn't this require a docker-compose.yml?

**Comment by nreamaroon** [comment]
Hi @luozhangwen, that command is ran inside the `/deploy` folder, you'll also find `docker-compose.yaml` inside there as well.

If you're still running into issues, could you please share which GPUs you're using and also provide the error log/output?

**Comment by luozhangwen** [comment]
> Hi @luozhangwen, that command is ran inside the `/deploy` folder, you'll also find `docker-compose.yaml` inside there as well.
> 
> If you're still running into issues, could you please share which GPUs you're using and also provide the error log/output?

Where can I get this deploy folder? 
I have try git clone from https://github.com/NVIDIA-NIM-Agent-Blueprints/digital-human.git  ( The document did not introduce it. -_-， I can't ran step by step. ),  And I found digital-human/deploy/docker-compose.yaml ， And execute common [sudo  USERID=$(id -u) docker compose --profile local-nim --profile milvus up -d]  , But, I got error "Access Deny" during docker pull nvcr.io/ohlfw0olaadg/ea-participants/rag-playground:24.06 ,  Can you help check if this Docker image exists?

**Comment by hwolff99** [comment]
I got this same issue.

**Comment by nreamaroon** [comment]
Hey @luozhangwen and @hwolff99! 

Just wanted to give you a heads-up that we did update `docker-compose.yaml` to point to a newer version of the RAG containers (2abda244c476d8cf881e06284dff8e0223b87b11) so you shouldn't be running into this issue anymore.
