### ISSUE TITLE
Error: Access Denied when Pulling Docker Image from NVIDIA Container Registry

### ISSUE THREAD

**Issue by jean-claude-ton-SWO** [NVIDIA-NIM-Agent-Blueprints/digital-human#4]
**Description**
I encountered an error while trying to pull the Docker image for the rag-application-text-chatbot-langchain service from the NVIDIA Container Registry. The error message indicates that access is denied.
**Error Message**
```
Error response from daemon: Head "https://nvcr.io/v2/ohlfw0olaadg/ea-rag-examples/rag-application-text-chatbot-langchain/manifests/24.07": denied: {"errors": [{"code": "DENIED", "message": "Access Denied"}]}
```

**Steps to Reproduce**
	1.	Followed tutorial until setup of (login docker, added api key)
	3.	Run the following command to start the Docker Compose services:

`sudo USERID=$(id -u) docker compose --profile local-nim --profile milvus up -d`

**Expected Behavior**
The command should successfully pull the required Docker image and start the services without any access errors.
**Actual Behavior**
The command fails with an "Access Denied" error when attempting to pull the Docker image from the NVIDIA Container Registry.

I cannot find [hlfw0olaadg/ea-rag-examples/rag-application-text-chatbot-langchain/ ](image: nvcr.io/ohlfw0olaadg/ea-rag-examples/rag-application-text-chatbot-langchain:24.07) in the catalog so tried with this one here https://catalog.ngc.nvidia.com/orgs/nvidia/teams/aiworkflows/containers/rag-application-text-chatbot-langchain/tags
which I was able to pull but then other parts broke.
Thanks

EDIT:
To test auth, I am able to pull images by running commands mentioned here https://build.nvidia.com/meta/llama-3_1-8b-instruct?snippet_tab=Docker
But cannot pull image using docker compose command

**Comment by nreamaroon** [comment]
Hey @jean-claude-ton-SWO! 

We're aware of the issue you mentioned. That specific container requires additional authentication, we're working on fixing this and will update here as soon as the issue has been resolved.

**Comment by jean-claude-ton-SWO** [comment]
Hey @nreamaroon 
Thanks for the heads up. Looking forward to try it out!

Meanwhile I was wondering if you think it makes sense to build the image myself from here https://github.com/NVIDIA/GenerativeAIExamples/blob/e85ddc1a015c7a422ca671332e7fa9924141fdfe/RAG/examples/basic_rag/langchain/docker-compose.yaml if that has the right configs.

**Comment by nreamaroon** [comment]
Yeah, that's the route we're going down as well! Glad you already found that registry for the public version of the `rag-application-text-chatbot-langchain` container, you'll also need to update the `rag-playground` container to the version currently on the NGC catalog.

Those container versions (24.08) have some additional downstream changes that we're testing internally. For example, the URL to access the UI would need to be updated to `http://localhost:3001/converse`. So you're more than welcome to give it a try, but just FYI there may be other downstream issues. Once we're able to validate everything, it'll be pushed to this repo, docs will be updated, and I'll also follow-up with you about it.

**Comment by nreamaroon** [comment]
Hey @jean-claude-ton-SWO! 

Just wanted to give you a heads-up that we did update `docker-compose.yaml` to point to the 24.08 containers (2abda244c476d8cf881e06284dff8e0223b87b11) so you shouldn't be running into this issue anymore.

**Comment by nreamaroon** [comment]
Hey @jean-claude-ton-SWO! 

Just wanted to give you a heads-up that we did update `docker-compose.yaml` to point to the 24.08 containers (2abda244c476d8cf881e06284dff8e0223b87b11) so you shouldn't be running into this issue anymore.
